/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segundoobligatoriop2.interfaz;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import segundoobligatoriop2.auxiliar.Mercado;

/**
 *
 * @author joaqu
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMenu
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        RegistroNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RegistroDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RegistroTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        RegistroVentaPor = new javax.swing.JComboBox<>();
        BotonLimpiarRegistro = new javax.swing.JButton();
        BotonAltaRegistro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BotonAbrirRegistro = new javax.swing.JButton();
        BotonCancelarRegistro = new javax.swing.JButton();
        AparicionImagenRegistro = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Inicio", jPanel4);

        jPanel1.setLayout(null);

        RegistroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroNombreActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroNombre);
        RegistroNombre.setBounds(260, 119, 120, 22);

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 119, 60, 16);

        jLabel2.setText("Descripcion:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 179, 90, 16);

        RegistroDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroDescripcion);
        RegistroDescripcion.setBounds(260, 179, 300, 22);

        jLabel3.setText("Tipo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 239, 26, 16);

        RegistroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruta", "Verdura" }));
        RegistroTipo.setName("");
        RegistroTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroTipoActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroTipo);
        RegistroTipo.setBounds(260, 229, 110, 20);

        jLabel4.setText("Venta por:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 279, 110, 16);

        RegistroVentaPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramo", "Unidad" }));
        jPanel1.add(RegistroVentaPor);
        RegistroVentaPor.setBounds(260, 279, 110, 22);

        BotonLimpiarRegistro.setText("Limpiar");
        BotonLimpiarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(BotonLimpiarRegistro);
        BotonLimpiarRegistro.setBounds(260, 339, 100, 40);

        BotonAltaRegistro.setText("Alta");
        jPanel1.add(BotonAltaRegistro);
        BotonAltaRegistro.setBounds(260, 399, 100, 40);

        jLabel5.setText("Imagen:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(670, 119, 60, 16);

        BotonAbrirRegistro.setText("Abrir");
        BotonAbrirRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonAbrirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbrirRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAbrirRegistro);
        BotonAbrirRegistro.setBounds(730, 422, 100, 30);

        BotonCancelarRegistro.setText("Cancelar");
        jPanel1.add(BotonCancelarRegistro);
        BotonCancelarRegistro.setBounds(890, 422, 100, 30);
        jPanel1.add(AparicionImagenRegistro);
        AparicionImagenRegistro.setBounds(70, 419, 180, 140);

        jTabbedPane4.addTab("Registros", jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Movimientos", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Consultas", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Generar archivo", jPanel3);

        getContentPane().add(jTabbedPane4);
        jTabbedPane4.setBounds(0, 0, 1060, 710);

        setBounds(0, 0, 1080, 724);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroNombreActionPerformed

    }//GEN-LAST:event_RegistroNombreActionPerformed

    private void RegistroDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroDescripcionActionPerformed

    private void RegistroTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroTipoActionPerformed

    private void BotonLimpiarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarRegistroActionPerformed
        LimpiarFormRegistro();
    }//GEN-LAST:event_BotonLimpiarRegistroActionPerformed

    private void BotonAbrirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbrirRegistroActionPerformed
        String Ruta = "";
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG", "JPG");
        jFileChooser.setFileFilter(filtrado);
        int respuesta = jFileChooser.showOpenDialog(this);

        if (respuesta == jFileChooser.APPROVE_OPTION) {
            Ruta = jFileChooser.getSelectedFile().getPath();
            Image mImagen = new ImageIcon(Ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(AparicionImagenRegistro.getWidth(), AparicionImagenRegistro.getHeight(), Image.SCALE_SMOOTH));
            AparicionImagenRegistro.setIcon(mIcono);
        }
    }//GEN-LAST:event_BotonAbrirRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AparicionImagenRegistro;
    private javax.swing.JButton BotonAbrirRegistro;
    private javax.swing.JButton BotonAltaRegistro;
    private javax.swing.JButton BotonCancelarRegistro;
    private javax.swing.JButton BotonLimpiarRegistro;
    private javax.swing.JTextField RegistroDescripcion;
    private javax.swing.JTextField RegistroNombre;
    private javax.swing.JComboBox<String> RegistroTipo;
    private javax.swing.JComboBox<String> RegistroVentaPor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables

    private void LimpiarFormRegistro() {
        RegistroDescripcion.setText("");
        RegistroNombre.setText("");
        
       
    }

}
