package segundoobligatoriop2.interfaz;


import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


public class InterfazRegistro extends javax.swing.JFrame {

    public InterfazRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        RegistroNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RegistroDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RegistroTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        RegistroVentaPor = new javax.swing.JComboBox<>();
        BotonLimpiarRegistro = new javax.swing.JButton();
        BotonAltaRegistro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BotonAbrirRegistro = new javax.swing.JButton();
        BotonCancelarRegistro = new javax.swing.JButton();
        AparicionImagenRegistro = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RegistroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroNombreActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroNombre);
        RegistroNombre.setBounds(200, 70, 120, 22);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 60, 16);

        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 90, 16);

        RegistroDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroDescripcion);
        RegistroDescripcion.setBounds(200, 130, 300, 22);

        jLabel3.setText("Tipo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 26, 16);

        RegistroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RegistroTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroTipoActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroTipo);
        RegistroTipo.setBounds(200, 180, 110, 20);

        jLabel4.setText("Venta por:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 230, 110, 16);

        RegistroVentaPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(RegistroVentaPor);
        RegistroVentaPor.setBounds(200, 230, 110, 22);

        BotonLimpiarRegistro.setText("Limpiar");
        BotonLimpiarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonLimpiarRegistro);
        BotonLimpiarRegistro.setBounds(200, 290, 100, 40);

        BotonAltaRegistro.setText("Alta");
        getContentPane().add(BotonAltaRegistro);
        BotonAltaRegistro.setBounds(200, 350, 100, 40);

        jLabel5.setText("Imagen:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 70, 60, 16);

        BotonAbrirRegistro.setText("Abrir");
        BotonAbrirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbrirRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAbrirRegistro);
        BotonAbrirRegistro.setBounds(670, 373, 100, 30);

        BotonCancelarRegistro.setText("Cancelar");
        getContentPane().add(BotonCancelarRegistro);
        BotonCancelarRegistro.setBounds(830, 373, 100, 30);
        getContentPane().add(AparicionImagenRegistro);
        AparicionImagenRegistro.setBounds(10, 370, 180, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroTipoActionPerformed

    private void BotonLimpiarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarRegistroActionPerformed
       LimpiarFormRegistro();
    }//GEN-LAST:event_BotonLimpiarRegistroActionPerformed

    private void BotonAbrirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbrirRegistroActionPerformed
        String Ruta="";
        JFileChooser jFileChooser= new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter ("JPG", "JPG");
        jFileChooser.setFileFilter(filtrado);
        int respuesta= jFileChooser.showOpenDialog(this);
        
        if(respuesta==jFileChooser.APPROVE_OPTION){
            Ruta= jFileChooser.getSelectedFile().getPath();
            
            Image mImagen = new ImageIcon(Ruta).getImage();
            ImageIcon mIcono = new ImageIcon (mImagen.getScaledInstance(AparicionImagenRegistro.getWidth(), AparicionImagenRegistro.getHeight(), Image.SCALE_SMOOTH));
            AparicionImagenRegistro.setIcon(mIcono);
        }
    }//GEN-LAST:event_BotonAbrirRegistroActionPerformed

    private void RegistroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroNombreActionPerformed
        
    }//GEN-LAST:event_RegistroNombreActionPerformed

    private void RegistroDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroDescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AparicionImagenRegistro;
    private javax.swing.JButton BotonAbrirRegistro;
    private javax.swing.JButton BotonAltaRegistro;
    private javax.swing.JButton BotonCancelarRegistro;
    private javax.swing.JButton BotonLimpiarRegistro;
    private javax.swing.JTextField RegistroDescripcion;
    private javax.swing.JTextField RegistroNombre;
    private javax.swing.JComboBox<String> RegistroTipo;
    private javax.swing.JComboBox<String> RegistroVentaPor;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void LimpiarFormRegistro() {
       RegistroDescripcion.setText("");
       RegistroNombre.setText("");
    }
}
